apiVersion: v1
kind: Template
metadata:
  name: insights-dashboard
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: dashboard
    spec:
      envName: ${ENV_NAME}
      deploymentRepo: https://github.com/RedHatInsights/insights-dashboard
      title: Dashboard
      image: ${IMAGE}:${IMAGE_TAG}
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/dashboard
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/insights-dashboard-frontend
