apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: insights-dashboard
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: dashboard
    spec:
      envName: ${ENV_NAME}
      deploymentRepo: https://github.com/RedHatInsights/insights-dashboard
      title: Dashboard
      image: ${IMAGE}:${IMAGE_TAG}
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/dashboard
      feoConfigEnabled: true
      widgetRegistry:
        - scope: landing
          module: ./RhelWidget
          featureFlag: widget.rhel.enable
          config:
            icon: RhelIcon
            title: Red Hat Enterprise Linux
          defaults:
            w: 1
            h: 4
            maxH: 10
            minH: 1
      searchEntries:
        - id: dashboard-insights
          title: Dashboard
          href: /insights/dashboard
          description: View details about your Red Hat Enterprise Linux systems.
          alt_title:
            - Dashboard
            - Insights
            - Lightspeed
            - RHEL
      module:
        manifestLocation: /apps/dashboard/fed-mods.json
        modules:
          - id: dashboard
            module: ./RootApp
            routes:
              - pathname: /insights/dashboard
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/insights-dashboard-frontend
